import { describe, it } from 'node:test';
import assert from 'node:assert/strict';

import { ALL_SUB_CATEGORY_IDS, RuleBasedValuer, WeightedRecyclerMatcher, lookupStat } from '@ewaste/shared';
import bundle from '../src/demo/bundle.json' with { type: 'json' };
import type { DemoBundle } from '../src/demo/index.ts';

/**
 * The demo bundle ships inside the APK and is what a field demo or a judge
 * actually sees. It is generated by a script, so nothing stops a bad
 * regeneration from shipping quietly - these tests are what stops it.
 */
const demo = bundle as unknown as DemoBundle;

describe('offline demo bundle', () => {
  it('covers every material the picker can offer', () => {
    // A category the collector can tap but which has no price is a dead end
    // in the middle of the demo.
    const missing = ALL_SUB_CATEGORY_IDS.filter((id) => !lookupStat(demo.priceIndex, id, demo.district));
    assert.deepEqual(missing, []);
  });

  it('offers only authorised facilities', () => {
    assert.ok(demo.recyclers.length > 0);
    for (const recycler of demo.recyclers) {
      assert.equal(recycler.authorizationStatus, 'authorized');
      assert.equal(recycler.place.district, demo.district);
    }
  });

  it('is still marked as synthetic', () => {
    assert.match(demo.note, /SYNTHETIC/);
    for (const recycler of demo.recyclers) {
      assert.ok(recycler.name.startsWith('[Demo] '), `unmarked facility: ${recycler.name}`);
    }
  });

  it('values a lot without a network', () => {
    const valuer = new RuleBasedValuer(demo.priceIndex);
    const result = valuer.estimate({
      subCategoryId: 'cable_copper_house',
      weightKg: 12,
      condition: 'intact',
      district: demo.district,
    });
    assert.ok(result.estimateInr > 0);
    assert.equal(result.basis, 'local_data', 'the demo district must have real local data');
  });

  it('finds a buyer without a network', () => {
    const result = new WeightedRecyclerMatcher().match({
      lot: {
        items: [
          { categoryId: 'cable', subCategoryId: 'cable_copper_house', approxWeightKg: 15 },
        ],
        totalWeightKg: 15,
        collectionPlace: { locality: 'Kothrud', district: demo.district, state: demo.state },
      } as never,
      collectorPoint: { lat: 18.5204, lon: 73.8567 },
      recyclers: demo.recyclers,
      priceIndex: demo.priceIndex,
      // Fixed so an expiring seed authorisation cannot silently empty the demo.
      now: new Date(demo.generatedAt),
    });
    assert.ok(result.matches.length > 0, 'the demo must always find at least one buyer');
    assert.ok(result.matches[0]!.estimatedPayoutInr > 0);
  });

  it('gives the ledger something to show, including recent activity', () => {
    assert.ok(demo.transactions.length >= 3);
    assert.ok(
      demo.transactions.some((t) => t.daysAgo <= 7),
      'at least one sale within the week, or the ledger opens empty',
    );
    for (const t of demo.transactions) assert.ok(t.finalPriceInr > 0);
  });

  it('stays small enough to sit in an APK', () => {
    const bytes = Buffer.byteLength(JSON.stringify(bundle));
    assert.ok(bytes < 250_000, `demo bundle too large: ${(bytes / 1024).toFixed(0)} KB`);
  });
});
